services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: oncity_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user_oncity
      MYSQL_PASSWORD: password_oncity
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
